### ISSUE TITLE
Tester feedback: Rate-limiting ads per user.

### ISSUE THREAD

**Issue by lukemulks** [brave-intl/bat-native-ads#119]
Per @mrose17 request, opening an issue after engaging with a tester that opened a thread on community.brave.com with feedback that they were seeing the same ad repeating too often. 

community.brave.com thread for reference: 

https://community.brave.com/t/seeing-the-same-ads-again-and-again-and-again/43157

The user provided a list of ads they observed after 2 hours of browsing: 
```
Here are the ads I got in two hours:

Uphold - Brave Partner
Buy and Sell Major Cryptos

Coinvest Vault
The Coinvest Vault Fonders Edition is ready to pre-order.

AirSwap
Buy and Sell Etereum tokens without any trading fees.

Guard My Gutter
Permanent Solution to Clogged Gutters. Get a Free Estimate!

papertrail
2 servers or 2000. Tail and search logs in real time. Archive and analyze years of logs.

Vimeo Stock
Come Explore Our Curated Collection.

AirSwap
Buy and sell ERC20 tokens wallet-to-wallet

LOGGY
Trace issues down to root cause, identify correlations, view source code, share with your team - all with SolarWinds Loggly.

AirSwap
Experience conversational trading on AirSwap today

LOGGY
Trace issues down to root cause, identify correlations, view source code, share with your team - all with SolarWindws Loggly.
```

After reviewing the feedback, I'm confident this issue will be resolved through: 

1. Improvements in frequency capping per campaign, and per ad, which will be resolved with the upcoming catalog update. See: https://github.com/brave/ads-serve/issues/110

2. Additional ad campaign inventory in rotation. We will be introducing roughly a dozen campaigns over the next week, many of which will be targeting similar categories that these ads were associated with.

**Comment by mrose17** [comment]
This is a problem with the product catalog, not the client code. Specifically, each of the notifications above is a different entry in the catalog. Unfortunately, some have identical (or very close) text and that is confusing, very confusing.  The two LOGGLY notifications above are in the catalog and have *identical* text.

If i was going to "fix" this, i'd say that the catalog importing process needs to detecting these kinds of things...
