### ISSUE TITLE
Use crypto::RandBytes for random number generation

### ISSUE THREAD

**Issue by riastradh-brave** [brave-intl/bat-native-ads#53]
Any random number generation in Brave should use crypto::RandBytes unless there's a strong reason not to.

https://github.com/brave-intl/bat-native-ads/blob/7c11b1bd97bab726d5d709beaca22cf369a8a0a4/src/math_helper.cc#L11-L16

(Not a blocking security issue because this is only for randomized delays, not for, say, key generation, and it's not clear that the threat model is articulated well enough to identify this as a flaw, but we should avoid things like the Mersenne twister in general.)

**Comment by tmancey** [comment]
Closing ticket as confirmed with @riastradh-brave using base::RandInt is ok
